import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/nav";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen w-full bg-white",inter.className, {'debug-screens': process.env.NODE_ENV === "development"})}>

{/*side bar */}
{/* manin page */}
<div className="p-8 w-full">{children}</div>

        
      </body>
    </html>
  );
}
