import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/SideNavbar";
import { cn } from "@/lib/utils";
import Topbar from "@/components/TopBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen w-full bg-white flex",inter.className, {'debug-screens': process.env.NODE_ENV === "development"})}>

{/*side bar */}
{/* <p className="border">Sidebar</p> */}

<>
<SideNavbar />
</>


<div className="flex-1 flex flex-col">
<Topbar />

{/* manin page */}
<div className="p-8 w-full">{children}</div>

</div> 
      </body>
    </html>
  );
}
